// SPDX-FileCopyrightText: © 2023 Olivier Meunier <olivier@neokraft.net>
//
// SPDX-License-Identifier: AGPL-3.0-only

package bleach

import "strings"

type tagRule uint8

const (
	tagKeep = 1 << iota
	tagKeepEmpty
	tagRemove
	tagRename
)

var blockTags = map[string]struct{}{
	"address":    {},
	"article":    {},
	"aside":      {},
	"blockquote": {},
	"canvas":     {},
	"dd":         {},
	"div":        {},
	"dl":         {},
	"dt":         {},
	"fieldset":   {},
	"figcaption": {},
	"figure":     {},
	"footer":     {},
	"form":       {},
	"h1":         {},
	"h2":         {},
	"h3":         {},
	"h4":         {},
	"h5":         {},
	"h6":         {},
	"header":     {},
	"hr":         {},
	"li":         {},
	"main":       {},
	"nav":        {},
	"noscript":   {},
	"ol":         {},
	"p":          {},
	"pre":        {},
	"section":    {},
	"table":      {},
	"tfoot":      {},
	"ul":         {},
	"video":      {},
}

// elementMap is the map of all known elements
// and the [tagRule]s that apply to them.
// As per https://developer.mozilla.org/en-US/docs/Web/HTML/Element
var elementMap = map[string]tagRule{
	"a":          tagKeep,
	"abbr":       tagKeep,
	"acronym":    tagKeep,
	"address":    tagKeep,
	"applet":     tagRemove,
	"area":       tagKeep | tagKeepEmpty,
	"article":    tagKeep,
	"aside":      tagKeep,
	"audio":      tagRemove,
	"b":          tagKeep,
	"base":       tagRemove | tagKeepEmpty,
	"bdi":        tagKeep,
	"bdo":        tagKeep,
	"big":        tagKeep,
	"blockquote": tagKeep,
	"body":       tagKeep,
	"br":         tagKeep | tagKeepEmpty,
	"button":     tagRemove,
	"canvas":     tagRemove,
	"caption":    tagKeep,
	"center":     tagKeep,
	"cite":       tagKeep,
	"code":       tagKeep,
	"col":        tagKeep | tagKeepEmpty,
	"command":    tagKeepEmpty,
	"colgroup":   tagKeep,
	"data":       tagKeep,
	"datalist":   tagKeep,
	"dd":         tagKeep,
	"del":        tagKeep,
	"details":    tagKeep,
	"dfn":        tagKeep,
	"dialog":     tagRemove,
	"dir":        tagKeep,
	"div":        tagKeep,
	"dl":         tagKeep,
	"dt":         tagKeep,
	"em":         tagKeep,
	"embed":      tagRemove | tagKeepEmpty,
	"fieldset":   tagRename,
	"figcaption": tagKeep,
	"figure":     tagKeep,
	"font":       tagRename,
	"footer":     tagKeep,
	"form":       tagRename,
	"frame":      tagRemove,
	"frameset":   tagRemove,
	"h1":         tagKeep,
	"h2":         tagKeep,
	"h3":         tagKeep,
	"h4":         tagKeep,
	"h5":         tagKeep,
	"h6":         tagKeep,
	"head":       tagRemove,
	"header":     tagKeep,
	"hgroup":     tagKeep,
	"hr":         tagKeep | tagKeepEmpty,
	"html":       tagKeep,
	"i":          tagKeep,
	"iframe":     tagRemove,
	"image":      tagKeep,
	"img":        tagKeep | tagKeepEmpty,
	"input":      tagRemove | tagKeepEmpty,
	"ins":        tagKeep,
	"kbd":        tagKeep,
	"keygen":     tagKeepEmpty,
	"label":      tagKeep,
	"legend":     tagKeep,
	"li":         tagKeep,
	"link":       tagRemove | tagKeepEmpty,
	"main":       tagKeep,
	"map":        tagKeep,
	"mark":       tagKeep,
	"marquee":    tagKeep,
	"menu":       tagKeep,
	"menuitem":   tagKeep | tagKeepEmpty,
	"meta":       tagRemove | tagKeepEmpty,
	"meter":      tagKeep,
	"nav":        tagKeep,
	"nobr":       tagKeep,
	"noembed":    tagRename,
	"noframes":   tagRename,
	"noscript":   tagRename,
	"object":     tagRemove,
	"ol":         tagKeep,
	"optgroup":   tagKeep,
	"option":     tagKeep,
	"output":     tagKeep,
	"p":          tagKeep,
	"param":      tagRemove | tagKeepEmpty,
	"picture":    tagKeep,
	"plaintext":  tagKeep,
	"portal":     tagRemove,
	"pre":        tagKeep,
	"progress":   tagKeep,
	"q":          tagKeep,
	"rb":         tagKeep,
	"rp":         tagKeep,
	"rt":         tagKeep,
	"rtc":        tagKeep,
	"ruby":       tagKeep,
	"s":          tagKeep,
	"samp":       tagKeep,
	"script":     tagRemove,
	"search":     tagKeep,
	"section":    tagKeep,
	"select":     tagRemove,
	"slot":       tagRemove,
	"small":      tagKeep,
	"source":     tagRemove | tagKeepEmpty,
	"span":       tagKeep,
	"strike":     tagKeep,
	"strong":     tagKeep,
	"style":      tagRemove,
	"sub":        tagKeep,
	"summary":    tagKeep,
	"sup":        tagKeep,
	"table":      tagKeep,
	"tbody":      tagKeep,
	"td":         tagKeep | tagKeepEmpty,
	"template":   tagRemove,
	"textarea":   tagRemove,
	"tfoot":      tagKeep,
	"th":         tagKeep | tagKeepEmpty,
	"thead":      tagKeep,
	"time":       tagKeep,
	"title":      tagRemove,
	"tr":         tagKeep,
	"track":      tagRemove | tagKeepEmpty,
	"tt":         tagKeep,
	"u":          tagKeep,
	"ul":         tagKeep,
	"var":        tagKeep,
	"video":      tagRemove,
	"wbr":        tagKeep | tagKeepEmpty,
	"xmp":        tagKeep,

	// MathML Core elements
	// curl -fsSL https://www.w3.org/Math/RelaxNG/mathml4/mathml4-core.rnc | grep -oE 'element [a-z-]+' | cut -d' ' -f2 | grep -v '^none$' | sort
	"annotation":     tagKeep,
	"annotation-xml": tagKeep,
	"maction":        tagKeep,
	"math":           tagKeep,
	"merror":         tagKeep,
	"mfrac":          tagKeep,
	"mi":             tagKeep,
	"mmultiscripts":  tagKeep,
	"mn":             tagKeep,
	"mo":             tagKeep,
	"mover":          tagKeep,
	"mpadded":        tagKeep,
	"mphantom":       tagKeep,
	"mprescripts":    tagKeep | tagKeepEmpty,
	"mroot":          tagKeep,
	"mrow":           tagKeep | tagKeepEmpty,
	"ms":             tagKeep,
	"mspace":         tagKeep | tagKeepEmpty,
	"msqrt":          tagKeep,
	"mstyle":         tagKeep,
	"msub":           tagKeep,
	"msubsup":        tagKeep,
	"msup":           tagKeep,
	"mtable":         tagKeep,
	"mtd":            tagKeep | tagKeepEmpty,
	"mtext":          tagKeep,
	"mtr":            tagKeep,
	"munder":         tagKeep,
	"munderover":     tagKeep,
	"semantics":      tagKeep,
}

var excludedChars = [][2]int{
	// CO block, except 0x09 (tab), 0x0A (LF), 0x0D (CR)
	{0x00, 0x08},
	{0x0B, 0x0C},
	{0x0E, 0x1F},

	// C1 block, except 0x85 (next line)
	{0x7F, 0x84},
	{0x86, 0x9F},

	// Surrogates
	{0xFDD0, 0xFDDF},
	{0xFFFE, 0xFFFF},

	{0x1FFFE, 0x1FFFF},
	{0x2FFFE, 0x2FFFF},
	{0x3FFFE, 0x3FFFF},
	{0x4FFFE, 0x4FFFF},
	{0x5FFFE, 0x5FFFF},
	{0x6FFFE, 0x6FFFF},
	{0x7FFFE, 0x7FFFF},
	{0x8FFFE, 0x8FFFF},
	{0x9FFFE, 0x9FFFF},
	{0xAFFFE, 0xAFFFF},
	{0xBFFFE, 0xBFFFF},
	{0xCFFFE, 0xCFFFF},
	{0xDFFFE, 0xDFFFF},
	{0xEFFFE, 0xEFFFF},
	{0xFFFFE, 0xFFFFF},
	{0x10FFFE, 0x10FFFF},
}

// ctrlReplacer is a string replacer for all invalid XML characters.
var ctrlReplacer = func() *strings.Replacer {
	repl := []string{}
	for _, t := range excludedChars {
		for i := t[0]; i <= t[1]; i++ {
			repl = append(repl, string(rune(i)), "")
		}
	}

	return strings.NewReplacer(repl...)
}()
