---
# SPDX-FileCopyrightText: © 2023 Olivier Meunier <olivier@neokraft.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

openapi: 3.0.0
info:
  version: 1.0.0
  title: Readeck API
  description: |
    # Introduction

    The Readeck API provides REST endpoints that can be used for any purpose, should it be a
    mobile application, a script, you name it.

    ## API Endpoint

    You can access this API on `__BASE_URI__`.

    Most of your requests and responses are using JSON as the exchange format.

    ## Test the API

    On this documentation, you can test every route.

    If you don't provide an API token in [Authentication](#auth), you can still test all the routes
    but note that the given curl examples only work with an API token.

    ## Authentication

    ### Create your own token

    If you're writing a script for yourself, the easiest way is to
    [generate an API token](../profile/tokens) that you can use using
    the `Bearer` HTTP authorization scheme.

    For example, you first request will look like:

    ```sh
    curl -H "Authorization: Bearer <TOKEN>" __BASE_URI__/bookmarks
    ```

    Or, in NodeJS:

    ```js
    fetch("__BASE_URI__/bookmarks", {
      headers: {
        "Authorization": "Bearer <TOKEN>",
      },
    })
    ```

    ### OAuth

    If you're writing an application, Readeck provides the OAuth 2 authorization code flow.

    #### Client Registration

    Before you can send your app's user to the authorization URL, you first need to register a
    client on the Readeck instance.

    Please refere to the [Client Creation Route](#post-/oauth/client) for more information.


    #### Authorization flow

    Once you received a `client_id`, you can build an authorization URL as explained in the
    [OAuth Token route](#post-/oauth/token). The rest of the process is following the OAuth 2
    specifications.


servers:
  - url: __BASE_URI__

components:
  securitySchemes:
    bearer:
      type: http
      scheme: Bearer

  schemas:
    $merge:
      - "types.yaml#.schemas"
      - "oauth/types.yaml#.schemas"
      - "bookmarks/types.yaml#.schemas"
      - "profile/types.yaml#.schemas"

security:
  - bearer: []

tags:
  - name: info
  - name: user profile
  - name: bookmarks
  - name: bookmark export
  - name: bookmark sync
  - name: bookmark sharing
  - name: bookmark labels
  - name: bookmark highlights
  - name: bookmark collections
  - name: bookmark import
  - name: dev tools
  - name: oauth client
  - name: oauth authorization

paths:
  $merge:
    - "info/routes.yaml#.routes"
    - "oauth/routes.yaml#.routes"
    - "profile/routes.yaml#.routes"
    - "bookmarks/routes.yaml#.routes"
    - "cookbook/routes.yaml#.routes"
